version: '3.8'

services:
  engage-gpt:
    # image: articodetz/engage-gpt:v0
    image: articodetz/engage-gpt:v2
    container_name: engage-gpt
    # command: ['docker-entrypoint.sh']
    # command: ["tail", "-f", "/app/server.js"]
    command: ['node', 'server.js'] 
    environment:
      - DISABLE_GPT4=1
      - ENABLE_BALANCE_QUERY=1
      - AZURE_URL=$AZURE_URL
      - AZURE_API_KEY=$AZURE_API_KEY
      - AZURE_API_VERSION=$AZURE_API_VERSION
      - DEFAULT_MODEL=$DEFAULT_MODEL
      - CUSTOM_MODELS=$CUSTOM_MODELS
      # - GOOGLE_API_KEY=$GOOGLE_API_KEY
      - CODE=$CODE
    ports:
      - 3000:3000

    networks:
      - gpt-network

networks:
  gpt-network:
    driver: bridge
